### ISSUE TITLE
Link text not appearing (Safari)

### ISSUE THREAD

**Issue by MJanick** [Chaseshak/BadgerNet#105]
I only saw this in Safari (not Chrome or Firefox). For some reason the first 2 links work but the text doesn't appear. If I hover over them I can see the text very very faintly.

**Comment by MJanick** [comment]
<img width="350" alt="links list" src="https://user-images.githubusercontent.com/26121773/33800056-67586098-dcfe-11e7-9189-2e91399e9473.png">

**Comment by rbrezynski** [comment]
I can't see any of them on Chrome. Maybe it's the ones that we've clicked? In any case definitely needs to be fixed.  
![screen shot 2017-12-09 at 5 30 20 pm](https://user-images.githubusercontent.com/26726721/33800519-af236104-dd06-11e7-8e01-a1cfa396bfdd.png)

**Comment by rbrezynski** [comment]
Seems to be working now
