### ISSUE TITLE
Calendar events are all stuck at top on first page load

### ISSUE THREAD

**Issue by rbrezynski** [Chaseshak/BadgerNet#43]
![screen shot 2017-11-27 at 4 20 19 pm](https://user-images.githubusercontent.com/26726721/33292464-f1118a2c-d38e-11e7-9a60-0d1c985c6ec3.png)
When you refresh it goes back to normal

**Comment by georgemblack** [comment]
Addressed in recent pull request. Positioning of elements no longer uses JavaScript, but ruby methods defined in `schedule_helper.rb`.
