### ISSUE TITLE
BadgerNet Emails

### ISSUE THREAD

**Issue by rbrezynski** [Chaseshak/BadgerNet#63]
Add a section on emails coming from BadgerNet to ask user to not respond to email because it will not go through. Currently if you respond get a failure email that looks like something broke. With a reminder to not respond it helps mitigate this. 
![screen shot 2017-12-04 at 6 32 42 pm](https://user-images.githubusercontent.com/26726721/33583772-98a8b110-d921-11e7-872e-a4518c75b17f.png)

**Comment by Chaseshak** [comment]
This is fixed via the commit above. Not sure why the issue didn't resolve. Closing.
