### ISSUE TITLE
Add validation to team section of announcements

### ISSUE THREAD

**Issue by rbrezynski** [Chaseshak/BadgerNet#67]
Currently I can create an announcement with no recipients. Open to suggestions on this. Either we add validation so that you have to select a team in order for the announcement to go through. Another solution is that everyone is automatically part of an "everyone" group so that by default everyone gets the message.

**Comment by Chaseshak** [comment]
I thought about this a while ago - but forgot to implement it. What we can do (since coaches see everything anyways) is scope something that doesn't select a specific team to the :athletes group which would achieve the same thing. Thoughts?

**Comment by rbrezynski** [comment]
I was thinking we should scope something that doesn't select a specific team (or user) to go to both :athletes and :coaches since it might be a boathouse wide announcement like "Boathouse closed this weekend"

**Comment by Chaseshak** [comment]
Can you give an example? Not sure I follow.

Everything goes to coaches always, they get to see all announcements.

**Comment by rbrezynski** [comment]
Oh like they automatically get sent everything too?
So yeah then it should be scoped to all :athletes

**Comment by Chaseshak** [comment]
Well I guess coaches wouldn't (without an implementation) get everything sent to them in an email, but they see all the announcements/documents regardless of what 'team' they were sent to.

**Comment by rbrezynski** [comment]
Right now I don't think any emails are actually being sent out to users anyway (is someone working on that?). But yes, maybe by default if no teams are selected then everyone can view but it doesn't get sent to anyone.

**Comment by Chaseshak** [comment]
Okay - I like that idea. And if that is the case, simply scoping to `:athlete` would work for allowing everyone to view. I believe @j2518966 was working on it.

**Comment by rbrezynski** [comment]
Great, that can be added to this https://github.com/Chaseshak/BadgerNet/pull/66 PR then.

**Comment by rbrezynski** [comment]
This has been fixed
