### ISSUE TITLE
Formatting on Team Page

### ISSUE THREAD

**Issue by rbrezynski** [Chaseshak/BadgerNet#73]
![screen shot 2017-12-04 at 8 10 10 pm](https://user-images.githubusercontent.com/26726721/33586466-28f241de-d92f-11e7-8255-7fcc1545ffa1.png)
Different font here than rest of site.
I'm guessing @georgemblack is fixing this in his current PR, but wanted to call this out since it's a more obvious formatting difference

**Comment by georgemblack** [comment]
Yup, got it

**Comment by rbrezynski** [comment]
This is been fixed
