### ISSUE TITLE
Remove Role in New Team modal isn't intuitive

### ISSUE THREAD

**Issue by rbrezynski** [Chaseshak/BadgerNet#79]
It doesn't make sense to have the remove role button inside of the new team modal. My suggestion would be to have two buttons New Team and Edit Team (or something like that), that each open separate modals. One that creates teams, and one that deletes teams to make it more intuitive for the user. Open to suggestions on how to make this make more sense

**Comment by Chaseshak** [comment]
Already working on this along with #77

**Comment by rbrezynski** [comment]
Assigning you to them so that we know they're being handled
