### ISSUE TITLE
Sort by role in user permission don’t work

### ISSUE THREAD

**Issue by rbrezynski** [Chaseshak/BadgerNet#93]
In the User Permissions page, if users are sorted by role by clicking on the corresponding button, users are sorted using no apparent criterion
--
I believe this is related to https://github.com/Chaseshak/BadgerNet/issues/92 which is switching coaches to athlete users if they are put on teams.

**Comment by Chaseshak** [comment]
Not related to #92, though @georgemblack's latest PR seems to resolve this... Might have had to do with how the table was contained. We should look at this one after #87 is merged.

**Comment by rbrezynski** [comment]
This has been fixed
